//Action Cons for Fetching data
export const GET_NOTE_RECEIEVE_DATA = "GET_NOTE_RECEIEVE_DATA";
export const GET_NOTE_COMPLETED_DATA = "GET_NOTE_COMPLETED_DATA";
//Action Cons for Create the data
export const CREATE_NOTE_RECEIEVE_DATA = "CREATE_NOTE_RECEIEVE_DATA";
export const CREATE_NOTE_COMPLETED_DATA = "CREATE_NOTE_COMPLETED_DATA";